CREATE TABLE IF NOT EXISTS DRAW_DL (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NUMBERS VARCHAR(20) NOT NULL,
    DRAW_DATE DATE NOT NULL,
    CREATE_DATE DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATE_DATE DATE
) ENGINE = INNODB;